version: '2'

networks:
  custom:
    driver: bridge

services:
  control:
    image: codespaces/ansible-control:v0.3.5
    ports:
      - "8000:8000"
    volumes:
      - ./code:/workspace
    networks:
      - custom
    domainname: codespaces.io
    hostname: control
    restart: always
  node1:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
       - "8080:80"
    networks:
      - custom
    domainname: codespaces.io
    hostname: lb
    restart: always
  node2:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
       - "81:80"
    networks:
      - custom
    domainname: codespaces.io
    hostname: app1
    restart: always
  node3:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
      - "82:80"
    networks:
      - custom
    domainname: codespaces.io
    hostname: app2
    restart: always
  node4:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
      - "3306:3306"
    networks:
      - custom
    domainname: codespaces.io
    hostname: db
    restart: always
