version: '2'

networks:
  custom:
    driver: bridge

services:
  control:
    image: codespaces/anisble-control:v0.1.0
    ports:
      - "8000:8000"
    volumes:
      - ./code:/workspace
    networks:
      - custom
    container_name: control
    domainname: codespaces.io
    hostname: control
    restart: always
  node1:
    image: codespaces/anisble-node-centos-6:v0.1.0
    container_name: lb
    ports:
       - "8080:80"
    networks:
      - custom
    domainname: codespaces.io
    hostname: lb
    restart: always
  node2:
    image: codespaces/anisble-node-centos-6:v0.1.0
    ports:
       - "81:80"
    networks:
      - custom
    container_name: app1
    domainname: codespaces.io
    hostname: app1
    restart: always
  node3:
    image: codespaces/anisble-node-ubuntu-1404:v0.1.0
    ports:
      - "82:80"
    networks:
      - custom
    container_name: app2
    domainname: codespaces.io
    hostname: app2
    restart: always
  node4:
    image: codespaces/anisble-node-centos-6:v0.1.0
    ports:
      - "3306:3306"
    networks:
      - custom
    container_name: db
    domainname: codespaces.io
    hostname: db
    restart: always
