version: '2'

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.61.0/24
services:
  control:
    image: codespaces/ansible-control:v0.4.0
    ports:
      - "8000:8000"
    volumes:
      - ./code:/workspace
    networks:
      custom:
        ipv4_address: 192.168.61.10
    domainname: codespaces.io
    hostname: control
    restart: always
  lb:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
       - "8080:8080"
       - "80:80"
    networks:
      custom:
        ipv4_address: 192.168.61.11
    domainname: codespaces.io
    hostname: lb
    restart: always
  app1:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
       - "8081:8080"
       - "81:80"
    networks:
      custom:
        ipv4_address: 192.168.61.12
    domainname: codespaces.io
    hostname: app1
    restart: always
  app2:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
      - "8082:8080"
      - "82:80"
    networks:
      custom:
        ipv4_address: 192.168.61.13
    domainname: codespaces.io
    hostname: app2
    restart: always
  db:
    image: codespaces/ansible-node-centos-6:v0.3.6
    ports:
      - "8083:8080"
      - "83:80"
      - "3306:3306"
    networks:
      custom:
        ipv4_address: 192.168.61.14
    domainname: codespaces.io
    hostname: db
    restart: always
